name: Nightly-Regression Tests

on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    - cron: "0 0 * * *"

jobs:
  Tox:
    runs-on: [self-hosted, linux, x64, anomalib]
    strategy:
      max-parallel: 1
    if: github.ref == 'refs/heads/main'
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v4
      - name: Install Tox
        run: pip install tox
      - name: Coverage
        run: tox -e nightly
      - name: Upload coverage result
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .tox/coverage.xml
  md-dead-link-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: AlexanderDokuchaev/md-dead-link-check@v0.7
        with:
          config: pyproject.toml
